# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name : Bruno Brasolin

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHdO'
    command: 'login'
- task: Docker@2
  inputs:
    buildContext: '$(Build.Repository.LocalPath)'
    containerRegistry: 'DockerHdO'
    repository: 'brunobrasolin/HdO'
    command: 'buildAndPush'
    tags: |
      latest
    Dockerfile: '**/Dockerfile'
- publish: $(System.DefaultWorkingDirectory)/stack.yml
  artifact: compose
